import './global.css';
import TaskComponent from './components/TasksComponent';

export const metadata = {
  title: 'Welcome to caddie-technical-test',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      
      <body>{children}
      <TaskComponent />
      </body>
    </html>
  );
}
